#define OPERATION_RESULT 0
#define DO_OUTSOURCEDMULTIPLICATION 1
#define DO_OUTSOURCEDHONNESTMULTIPLICATION 2
#define DO_COMPARISONFIRSTPART 3
#define DO_COMPARISONSECONDPART 4
#define PRODUCE_REPLACEMENTVECTOR 666


